server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://rm-bp1446ke5e0u8y0sm8o.mysql.rds.aliyuncs.com:3306/micromall?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Peng789852@
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      max-wait: 60000
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      validation-query: SELECT 1 FROM DUAL
  #rabbitmq相关配置
#  rabbitmq:
#    host: 192.168.232.198
#    port: 5672
#    username: admin
#    password: admin
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /actuator/**
      - /druid/**
      - /user/login
      - /user/register
      - /upload/product/**
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5tKvymt6qnUVo5DMt652 # 访问身份验证中用到用户标识
    accessKeySecret: 8CRD3U7mggkEszt5gXCZNRH8FfJYly # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: mall-again # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://yangguo.natapp1.cc/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: mall-again/images/ # 上传文件夹路径前缀

#logstash:
#  host: localhost
#  port: 8084
#upload:
#  product:
#    images: D:/temp/product/images